//
//  AlabamaPlates.swift
//  License Plate Search
//
//  Created by Jared Detro on 6/30/20.
//  Copyright © 2020 Jared Detro. All rights reserved.
//

import Foundation

extension State {
    static let alabama = State(name: "Alabama", plates: [
        Plate(plateName: "Bicentennial", imageCounter: 0),
        Plate(plateName: "God Bless America", imageCounter: 1),
        Plate(plateName: "Don't Tread on Me", imageCounter: 2),
        Plate(plateName: "Cattlemen", imageCounter: 3),
        Plate(plateName: "Cahaba River", imageCounter: 4),
        Plate(plateName: "Ducks Unlimited", imageCounter: 5),
        Plate(plateName: "Environmental", imageCounter: 6),
        Plate(plateName: "Farming Feeds", imageCounter: 7),
        Plate(plateName: "Forests Forever", imageCounter: 8),
        Plate(plateName: "Forever Wild", imageCounter: 9),
        Plate(plateName: "Freshwater Fishing", imageCounter: 10),
        Plate(plateName: "National Wild Turkey Federation", imageCounter: 11),
        Plate(plateName: "Saltwater Fishing", imageCounter: 12),
        Plate(plateName: "Alabama State Parks", imageCounter: 13),
        Plate(plateName: "Treasure Forest", imageCounter: 14),
        Plate(plateName: "Wildlife Federation", imageCounter: 15),
        Plate(plateName: "Alabama Poultry Foundation", imageCounter: 16),
        Plate(plateName: "Friends of Coal", imageCounter: 17),
        Plate(plateName: "Whitetail Warrior Project", imageCounter: 18),
        Plate(plateName: "Autism Acceptance", imageCounter: 19),
        Plate(plateName: "Breast Cancer Research", imageCounter: 20),
        Plate(plateName: "Choose Life Support Adoption", imageCounter: 21),
        Plate(plateName: "Curing Childhood Cancer", imageCounter: 22),
        Plate(plateName: "Fight Breast Cancer", imageCounter: 23),
        Plate(plateName: "Fighting Cystic Fibrosis", imageCounter: 24),
        Plate(plateName: "Freemason", imageCounter: 25),
        Plate(plateName: "Habitat For Humanity", imageCounter: 26),
        Plate(plateName: "Helping Schools", imageCounter: 27),
        Plate(plateName: "Hope For Kids With Diabetes", imageCounter: 28),
        Plate(plateName: "Mending Kids Hearts", imageCounter: 29),
        Plate(plateName: "Ovarian Cancer Research", imageCounter: 30),
        Plate(plateName: "Ronald McDonald House Charities", imageCounter: 31),
        Plate(plateName: "Save The Saturn V", imageCounter: 32),
        Plate(plateName: "Sickle Cell Awareness", imageCounter: 33),
        Plate(plateName: "Shriners", imageCounter: 34),
        Plate(plateName: "Spay Neuter", imageCounter: 35),
        Plate(plateName: "Stop Domestic Violence", imageCounter: 36),
        Plate(plateName: "Children's Trust Fund", imageCounter: 37),
        Plate(plateName: "King's Home", imageCounter: 38),
        Plate(plateName: "Letter Carrier", imageCounter: 39),
        Plate(plateName: "Colon Cancer Awareness", imageCounter: 40),
        Plate(plateName: "Civitan", imageCounter: 41),
        Plate(plateName: "Prostate Cancer Research", imageCounter: 42),
        Plate(plateName: "Support Our Troops", imageCounter: 43),
        Plate(plateName: "Thank a Lineman", imageCounter: 44),
        Plate(plateName: "Prince Hall Grand Lodge", imageCounter: 45),
        Plate(plateName: "Alabama A & M", imageCounter: 46),
        Plate(plateName: "Alabama State University", imageCounter: 47),
        Plate(plateName: "Athens State University", imageCounter: 48),
        Plate(plateName: "Auburn University", imageCounter: 49),
        Plate(plateName: "Auburn University at Montgomery", imageCounter: 50),
        Plate(plateName: "Birmingham - Southern College", imageCounter: 51),
        Plate(plateName: "Faulkner University", imageCounter: 52),
        Plate(plateName: "Florida State University", imageCounter: 53),
        Plate(plateName: "Huntingdon College", imageCounter: 54),
        Plate(plateName: "Jacksonville State University", imageCounter: 55),
        Plate(plateName: "Jefferson State Community College", imageCounter: 56),
        Plate(plateName: "Judson College", imageCounter: 57),
        Plate(plateName: "Miles College", imageCounter: 58),
        Plate(plateName: "Mississippi State University", imageCounter: 59),
        Plate(plateName: "Oakwood University", imageCounter: 60),
        Plate(plateName: "Samford University", imageCounter: 61),
        Plate(plateName: "Selma University", imageCounter: 62),
        Plate(plateName: "Spring Hill College", imageCounter: 63),
        Plate(plateName: "Stillman College", imageCounter: 64),
        Plate(plateName: "Talladega College", imageCounter: 65),
        Plate(plateName: "Troy University", imageCounter: 66),
        Plate(plateName: "Tuskegee University", imageCounter: 67),
        Plate(plateName: "University of Alabama", imageCounter: 68),
        Plate(plateName: "University of Alabama at Birmingham", imageCounter: 69),
        Plate(plateName: "University of Alabama in Huntsville", imageCounter: 70),
        Plate(plateName: "University of Georgia", imageCounter: 71),
        Plate(plateName: "University of Mississippi", imageCounter: 72),
        Plate(plateName: "University of Mobile", imageCounter: 73),
        Plate(plateName: "University of Montevallo", imageCounter: 74),
        Plate(plateName: "University of North Alabama", imageCounter: 75),
        Plate(plateName: "University of South Alabama", imageCounter: 76),
        Plate(plateName: "University of West Alabama", imageCounter: 77),
        Plate(plateName: "Educator", imageCounter: 78),
        Plate(plateName: "Delta Sigma Theta Sorority", imageCounter: 79),
        Plate(plateName: "Alpha Kappa Alpha Sorority", imageCounter: 80),
        Plate(plateName: "Alpha Phi Alpha Fraternity", imageCounter: 81),
        Plate(plateName: "Omega Psi Phi Fraternity", imageCounter: 82),
        Plate(plateName: "Kappa Alpha Psi", imageCounter: 83),
        Plate(plateName: "Zeta Phi Beta Sorority", imageCounter: 84),
        Plate(plateName: "Ambulance & Hearse", imageCounter: 85),
        Plate(plateName: "EMS", imageCounter: 86),
        Plate(plateName: "Alabama Firefighters", imageCounter: 87),
        Plate(plateName: "Fraternal Order Of Police", imageCounter: 88),
        Plate(plateName: "In Memory Of", imageCounter: 89),
        Plate(plateName: "Law Enforcement Memorial", imageCounter: 90),
        Plate(plateName: "Nurses", imageCounter: 91),
        Plate(plateName: "Professional Firefighter", imageCounter: 92),
        Plate(plateName: "Rescue Squad", imageCounter: 93),
        Plate(plateName: "Retired Firefighter", imageCounter: 94),
        Plate(plateName: "Volunteer Fire Department", imageCounter: 95),
        Plate(plateName: "K9 for Vets", imageCounter: 96),
        Plate(plateName: "Huntsville Hospital", imageCounter: 97),
        Plate(plateName: "County", imageCounter: 98),
        Plate(plateName: "County Motorcycle", imageCounter: 99),
        Plate(plateName: "County Disability Access", imageCounter: 100),
        Plate(plateName: "Government Loaned", imageCounter: 101),
        Plate(plateName: "Municipal", imageCounter: 102),
        Plate(plateName: "Municipal Disability Access", imageCounter: 103),
        Plate(plateName: "Municipal Motorcycle", imageCounter: 104),
        Plate(plateName: "Public Utility Department", imageCounter: 105),
        Plate(plateName: "State Disability Access", imageCounter: 106),
        Plate(plateName: "State Government", imageCounter: 107),
        Plate(plateName: "State Government Motorcycle", imageCounter: 108),
        Plate(plateName: "State Motor Pool", imageCounter: 109),
        Plate(plateName: "State National Guard", imageCounter: 110),
        Plate(plateName: "Consular Official", imageCounter: 111),
        Plate(plateName: "Active Reserve", imageCounter: 112),
        Plate(plateName: "U.S. Air Force", imageCounter: 113),
        Plate(plateName: "Alabama State Defense Force", imageCounter: 114),
        Plate(plateName: "U.S. Army", imageCounter: 115),
        Plate(plateName: "Atomic Veteran", imageCounter: 116),
        Plate(plateName: "Battle of the Bulge", imageCounter: 117),
        Plate(plateName: "Alabama Bronze Star", imageCounter: 118),
        Plate(plateName: "U.S. Coast Guard", imageCounter: 119),
        Plate(plateName: "Desert Shield Desert Storm", imageCounter: 120),
        Plate(plateName: "Alabama Distinguished Flying Cross", imageCounter: 121),
        Plate(plateName: "Global War on Terrorism", imageCounter: 122),
        Plate(plateName: "Alabama Korean War Veteran", imageCounter: 123),
        Plate(plateName: "Legion of Valor", imageCounter: 124),
        Plate(plateName: "Marine Corps", imageCounter: 125),
        Plate(plateName: "Alabama Medal of Honor", imageCounter: 126),
        Plate(plateName: "U.S. Merchant Marine", imageCounter: 127),
        Plate(plateName: "Alabama National Guard", imageCounter: 128),
        Plate(plateName: "U.S. Navy", imageCounter: 129),
        Plate(plateName: "Operation Enduring Freedom Afghanistan Veteran", imageCounter: 130),
        Plate(plateName: "Operation Iraqi Freedom Veteran", imageCounter: 131),
        Plate(plateName: "Alabama Pearl Harbor Survivor", imageCounter: 132),
        Plate(plateName: "Prisoner of War", imageCounter: 133),
        Plate(plateName: "Purple Heart - Combat Wounded", imageCounter: 134),
        Plate(plateName: "Silver Star", imageCounter: 135),
        Plate(plateName: "Vietnam Veteran", imageCounter: 136),
        Plate(plateName: "American Campaign", imageCounter: 137),
        Plate(plateName: "Asiatic Pacific Campaign", imageCounter: 138),
        Plate(plateName: "European Campaign", imageCounter: 139),
        Plate(plateName: "U.S. Armed Forces Retired - Air Force", imageCounter: 140),
        Plate(plateName: "U.S. Armed Forces Retired - Army", imageCounter: 141),
        Plate(plateName: "U.S. Armed Forces Retired - Coast Guard", imageCounter: 142),
        Plate(plateName: "U.S. Armed Forces Retired - Marine Corps", imageCounter: 143),
        Plate(plateName: "U.S. Armed Forces Retired - National Guard", imageCounter: 144),
        Plate(plateName: "U.S. Armed Forces Retired - Navy", imageCounter: 145),
        Plate(plateName: "Disabled Veteran - Air Force", imageCounter: 146),
        Plate(plateName: "Disabled Veteran - Army", imageCounter: 147),
        Plate(plateName: "Disabled Veteran - Coast Guard", imageCounter: 148),
        Plate(plateName: "Disabled Veteran - Marine Corps", imageCounter: 149),
        Plate(plateName: "Disabled Veteran - Merchant Marine", imageCounter: 150),
        Plate(plateName: "Disabled Veteran - National Guard", imageCounter: 151),
        Plate(plateName: "Disabled Veteran - Navy", imageCounter: 152),
        Plate(plateName: "Gold Star Family", imageCounter: 153),
        Plate(plateName: "Sons Of Confederate Veterans", imageCounter: 154),
        Plate(plateName: "Alabama Home Builders", imageCounter: 155),
        Plate(plateName: "Amateur Radio", imageCounter: 156),
        Plate(plateName: "Barber Vintage Motorsports Museum", imageCounter: 157),
        Plate(plateName: "Realtor", imageCounter: 158),
        Plate(plateName: "Support The Arts", imageCounter: 159),
        Plate(plateName: "Square and Round Dance", imageCounter: 160),
        Plate(plateName: "Rotary International", imageCounter: 161),
        Plate(plateName: "Chase Elliott", imageCounter: 162),
        Plate(plateName: "Clint Bowyer", imageCounter: 163),
        Plate(plateName: "Dale Earnhardt", imageCounter: 164),
        Plate(plateName: "Dale Earnhardt Jr.", imageCounter: 165),
        Plate(plateName: "Ford Racing", imageCounter: 166),
        Plate(plateName: "Jimmie Johnson", imageCounter: 167),
        Plate(plateName: "Kevin Harvick", imageCounter: 168),
        Plate(plateName: "Kyle Busch", imageCounter: 169),
        Plate(plateName: "Martin Truex Jr.", imageCounter: 170),
        Plate(plateName: "NASCAR", imageCounter: 171),
        Plate(plateName: "NASCAR Track", imageCounter: 172),
        Plate(plateName: "Richard Petty", imageCounter: 173),
        Plate(plateName: "The Alabama Gang", imageCounter: 174),
        Plate(plateName: "Alabama Tennis Foundation", imageCounter: 175),
        Plate(plateName: "I Share the Road", imageCounter: 176),
        Plate(plateName: "Apportioned", imageCounter: 177),
        Plate(plateName: "Commercial Bus", imageCounter: 178),
        Plate(plateName: "Cotton Module", imageCounter: 179),
        Plate(plateName: "Dealer", imageCounter: 180),
        Plate(plateName: "Dealer - Motorcycle", imageCounter: 181),
        Plate(plateName: "Dealer Transit", imageCounter: 182),
        Plate(plateName: "Dealer Transit - Motorcycle", imageCounter: 183),
        Plate(plateName: "Farm Truck, Truck Tractor", imageCounter: 184),
        Plate(plateName: "For Hire, Limited", imageCounter: 185),
        Plate(plateName: "Forest Product Truck", imageCounter: 186),
        Plate(plateName: "Manufacturer", imageCounter: 187),
        Plate(plateName: "Manufacturer - Motorcycle", imageCounter: 188),
        Plate(plateName: "Mini-truck", imageCounter: 189),
        Plate(plateName: "Permanent Trailer", imageCounter: 190),
        Plate(plateName: "P1 (Truck 8,001-10,000 lbs. GVW)", imageCounter: 191),
        Plate(plateName: "Recreational Vehicle & Motor Home", imageCounter: 192),
        Plate(plateName: "Recreational Vehicle & Motor Home (Old)", imageCounter: 193),
        Plate(plateName: "Rental Trailer", imageCounter: 194),
        Plate(plateName: "Semi Trailer", imageCounter: 195),
        Plate(plateName: "Standard Motorcycle", imageCounter: 196),
        Plate(plateName: "Standard Motorcycle Disability Access", imageCounter: 197),
        Plate(plateName: "Standard Passenger", imageCounter: 198),
        Plate(plateName: "Standard Passenger Disability Access", imageCounter: 199),
        Plate(plateName: "Taxi", imageCounter: 200),
        Plate(plateName: "Travel Trailer", imageCounter: 201),
        Plate(plateName: "Truck, Truck Tractor", imageCounter: 202),
        Plate(plateName: "Utility Trailer", imageCounter: 203),
        Plate(plateName: "Vintage Vehicle", imageCounter: 204),
        Plate(plateName: "XA Truck (10,001-12,000 lbs. GVW)", imageCounter: 205),
    ])
}
