//
//  Arizona.swift
//  License Plate Search
//
//  Created by Jared Detro on 6/30/20.
//  Copyright © 2020 Jared Detro. All rights reserved.
//

import Foundation

extension State {
    static let arizona = State(name: "Arizona", plates: [
        Plate(plateName: "Arizona Standard", imageCounter: 0),
        Plate(plateName: "Disability", imageCounter: 1),
        Plate(plateName: "Centennial", imageCounter: 2),
        Plate(plateName: "Golden Rule", imageCounter: 3),
        Plate(plateName: "Hearing Impaired", imageCounter: 4),
        Plate(plateName: "Arizona In God We Trust", imageCounter: 5),
        Plate(plateName: "Alternative Fuel", imageCounter: 6),
        Plate(plateName: "Arizona Agriculture", imageCounter: 7),
        Plate(plateName: "Arizona Sportsmen for Wildlife Conservation", imageCounter: 8),
        Plate(plateName: "Energy Efficient", imageCounter: 9),
        Plate(plateName: "Environmental ", imageCounter: 10),
        Plate(plateName: "Keep Arizona Beautiful", imageCounter: 12),
        Plate(plateName: "Pet Friendly - Spay and Neuter", imageCounter: 13),
        Plate(plateName: "Arizona Coyotes Foundation", imageCounter: 14),
        Plate(plateName: "Barrett-Jackson", imageCounter: 15),
        Plate(plateName: "Boy Scouts of America", imageCounter: 16),
        Plate(plateName: "Child Abuse Prevention", imageCounter: 17),
        Plate(plateName: "Choose Life ", imageCounter: 18),
        Plate(plateName: "Girl Scouts", imageCounter: 19),
        Plate(plateName: "Hunger Relief", imageCounter: 20),
        Plate(plateName: "Freemason ", imageCounter: 21),
        Plate(plateName: "Pink Ribbon - Cancer Awareness", imageCounter: 22),
        Plate(plateName: "Transplantation Awareness (Organ Donor)", imageCounter: 23),
        Plate(plateName: "Arizona State University", imageCounter: 24),
        Plate(plateName: "Character Education", imageCounter: 25),
        Plate(plateName: "Extraordinary Educators", imageCounter: 26),
        Plate(plateName: "Grand Canyon University", imageCounter: 27),
        Plate(plateName: "Midwestern University", imageCounter: 28),
        Plate(plateName: "Northern Arizona University", imageCounter: 29),
        Plate(plateName: "Thunderbird School of Global Management", imageCounter: 30),
        Plate(plateName: "University of Arizona", imageCounter: 31),
        Plate(plateName: "University of Phoenix", imageCounter: 32),
        Plate(plateName: "Veteran", imageCounter: 33),
        Plate(plateName: "Veteran - Motorcycle", imageCounter: 34),
        Plate(plateName: "Childhood Cancer Research", imageCounter: 35),
        Plate(plateName: "Families of Fallen Police Officers", imageCounter: 36),
        Plate(plateName: "Fire Fighter", imageCounter: 37),
        Plate(plateName: "Firefighter Safety Training", imageCounter: 38),
        Plate(plateName: "First Responder", imageCounter: 39),
        Plate(plateName: "First Responder - Motorcycle", imageCounter: 40),
        Plate(plateName: "Fraternal Order of Police", imageCounter: 41),
        Plate(plateName: "Honorary Foreign Consul", imageCounter: 42),
        Plate(plateName: "Navajo Nation", imageCounter: 43),
        Plate(plateName: "San Carlos Apache Tribe", imageCounter: 44),
        Plate(plateName: "White Mountain Apache Tribe", imageCounter: 45),
        Plate(plateName: "Congressional Medal of Honor", imageCounter: 46),
        Plate(plateName: "Former Prisoner of War", imageCounter: 47),
        Plate(plateName: "Gold Star Family", imageCounter: 48),
        Plate(plateName: "Gold Star Family - Motorcycle", imageCounter: 49),
        Plate(plateName: "Leigon of Valor", imageCounter: 50),
        Plate(plateName: "Luke Air Force Base", imageCounter: 51),
        Plate(plateName: "Luke Air Force Base - Motorcycle", imageCounter: 52),
        Plate(plateName: "Support Freedom", imageCounter: 53),
        Plate(plateName: "Support Freedom - Motorcycle", imageCounter: 54),
        Plate(plateName: "National Guard", imageCounter: 55),
        Plate(plateName: "Pearl Harbor Survivor", imageCounter: 56),
        Plate(plateName: "Purple Heart", imageCounter: 57),
        Plate(plateName: "Purple Heart - Motorcycle", imageCounter: 58),
        Plate(plateName: "U.S. Marine Corps", imageCounter: 59),
        Plate(plateName: "U.S. Marine Corps - Motorcycle", imageCounter: 60),
        Plate(plateName: "Women Veterans", imageCounter: 61),
        Plate(plateName: "Arizona Amateur Radio", imageCounter: 62),
        Plate(plateName: "Arizona Highways", imageCounter: 63),
        Plate(plateName: "Arizona Historical Society", imageCounter: 64),
        Plate(plateName: "Arizona Science Center", imageCounter: 65),
        Plate(plateName: "Channel 8 PBS", imageCounter: 66),
        Plate(plateName: "Route 66", imageCounter: 67),
        Plate(plateName: "Route 66 - Motorcycle", imageCounter: 68),
        Plate(plateName: "Arizona Cardinals", imageCounter: 69),
        Plate(plateName: "Arizona Diamondbacks", imageCounter: 70),
        Plate(plateName: "Phoenix International Raceway", imageCounter: 71),
        Plate(plateName: "Phoenix Suns", imageCounter: 72),
        Plate(plateName: "Southwest PGA", imageCounter: 73),
        Plate(plateName: "Special Olympics Arizona", imageCounter: 74),
        Plate(plateName: "Classic Car", imageCounter: 75),
        Plate(plateName: "Farm Vehicle ", imageCounter: 76),
        Plate(plateName: "Historic Vehicle ", imageCounter: 77),
        Plate(plateName: "Horseless Carriage", imageCounter: 78),
        Plate(plateName: "Street Rod", imageCounter: 79)
    ])
}
