//
//  Arkansas.swift
//  License Plate Search
//
//  Created by Jared Detro on 6/30/20.
//  Copyright © 2020 Jared Detro. All rights reserved.
//

import Foundation

extension State {
    static let arkansas = State(name: "Arkansas", plates: [
    Plate(plateName: "Arkansas Standard", imageCounter: 0),
    Plate(plateName: "In God We Trust ", imageCounter: 1),
    Plate(plateName: "Disabled", imageCounter: 2),
    Plate(plateName: "Arkansas State Parks", imageCounter: 3),
    Plate(plateName: "Rice Council", imageCounter: 4),
    Plate(plateName: "Department of Conservation Districts", imageCounter: 5),
    Plate(plateName: "Ducks Unlimited - Design 1", imageCounter: 6),
    Plate(plateName: "Ducks Unlimited - Design 2", imageCounter: 7),
    Plate(plateName: "Ducks Unlimited - Design 3", imageCounter: 8),
    Plate(plateName: "Farm to Market Bus", imageCounter: 9),
    Plate(plateName: "Game & Fish Dog", imageCounter: 10),
    Plate(plateName: "Game & Fish Crappie Fish", imageCounter: 11),
    Plate(plateName: "Game & Fish Deer (Old)", imageCounter: 12),
    Plate(plateName: "Game & Fish Ivory Billed Woodpecker", imageCounter: 13),
    Plate(plateName: "Game & Fish Black Bear", imageCounter: 14),
    Plate(plateName: "Game & Fish Black Lab", imageCounter: 15),
    Plate(plateName: "Game & Fish Butterfly", imageCounter: 16),
    Plate(plateName: "Game & Fish Deer - Design 1", imageCounter: 17),
    Plate(plateName: "Game & Fish Deer - Design 2", imageCounter: 18),
    Plate(plateName: "Game & Fish Eagle", imageCounter: 19),
    Plate(plateName: "Game & Fish Elk", imageCounter: 20),
    Plate(plateName: "Game & Fish Hummingbird", imageCounter: 21),
    Plate(plateName: "Game & Fish Largemouth Bass", imageCounter: 22),
    Plate(plateName: "Game & Fish Mallard Duck", imageCounter: 23),
    Plate(plateName: "Game & Fish Rainbow Trout", imageCounter: 24),
    Plate(plateName: "Game & Fish Red Fox", imageCounter: 25),
    Plate(plateName: "Game & Fish Smallmouth Bass", imageCounter: 26),
    Plate(plateName: "Game & Fish Squirrel", imageCounter: 27),
    Plate(plateName: "Game & Fish Wild Turkey", imageCounter: 28),
    Plate(plateName: "Game & Fish Pintail Duck", imageCounter: 29),
    Plate(plateName: "National Wild Turkey Federation  ", imageCounter: 30),
    Plate(plateName: "Quail Forever", imageCounter: 31),
    Plate(plateName: "Court Appointed Special Advocates", imageCounter: 32),
    Plate(plateName: "Down Syndrome Association", imageCounter: 33),
    Plate(plateName: "Autism Awareness", imageCounter: 34),
    Plate(plateName: "Border City Taxi Cab", imageCounter: 35),
    Plate(plateName: "Boy Scout, Girl Scout, & Orphanages", imageCounter: 36),
    Plate(plateName: "Arkansas Boy Scouts of America", imageCounter: 37),
    Plate(plateName: "Arkansas Childhood Cancer Research", imageCounter: 38),
    Plate(plateName: "Arkansas Choose Life", imageCounter: 39),
    Plate(plateName: "Dr. Martin Luther King, Jr.", imageCounter: 40),
    Plate(plateName: "Dr. Martin Luther King, Jr. Commission", imageCounter: 41),
    Plate(plateName: "Arkansas' Freemason's", imageCounter: 42),
    Plate(plateName: "Grand Lodge", imageCounter: 43),
    Plate(plateName: "Hospice & Palliative Care", imageCounter: 44),
    Plate(plateName: "Adopt a Pet", imageCounter: 45),
    Plate(plateName: "National Multiple Sclerosis Society", imageCounter: 46),
    Plate(plateName: "Organ Donor", imageCounter: 47),
    Plate(plateName: "Arkansas' Prince Hall Grand Lodge", imageCounter: 48),
    Plate(plateName: "Support Animal Rescue & Shelters", imageCounter: 49),
    Plate(plateName: "Support Our Troops ", imageCounter: 50),
    Plate(plateName: "Support Spay or Neutering", imageCounter: 51),
    Plate(plateName: "Cure Breast Cancer", imageCounter: 52),
    Plate(plateName: "4-H Develops Arkansas Youth", imageCounter: 53),
    Plate(plateName: "Arkansas School for the Deaf", imageCounter: 54),
    Plate(plateName: "Arkansas State University", imageCounter: 55),
    Plate(plateName: "Arkansas Tech University", imageCounter: 56),
    Plate(plateName: "College of the Ouachitas", imageCounter: 57),
    Plate(plateName: "Committed to Education (Old)", imageCounter: 58),
    Plate(plateName: "Committed to Education", imageCounter: 59),
    Plate(plateName: "Harding University", imageCounter: 60),
    Plate(plateName: "Hearse", imageCounter: 61),
    Plate(plateName: "Henderson State University", imageCounter: 62),
    Plate(plateName: "Hendrix College", imageCounter: 63),
    Plate(plateName: "John Brown University", imageCounter: 64),
    Plate(plateName: "Kappa Alpha PSI Fraternity", imageCounter: 65),
    Plate(plateName: "Lyon College", imageCounter: 66),
    Plate(plateName: "Mid-South Community College", imageCounter: 67),
    Plate(plateName: "National Park Community College", imageCounter: 68),
    Plate(plateName: "Northwest Arkansas Community College", imageCounter: 69),
    Plate(plateName: "Omega PSI PHI Fraternity", imageCounter: 70),
    Plate(plateName: "Ouachita Baptist University", imageCounter: 71),
    Plate(plateName: "Phi Beta Sigma Fraternity", imageCounter: 72),
    Plate(plateName: "Southern Arkansas University", imageCounter: 73),
    Plate(plateName: "University of Arkansas", imageCounter: 74),
    Plate(plateName: "University of Arkansas at Little Rock", imageCounter: 75),
    Plate(plateName: "University of Arkansas at Monticello", imageCounter: 76),
    Plate(plateName: "University of Arkansas Pine Bluff", imageCounter: 77),
    Plate(plateName: "University of Arkansas Fort Smith", imageCounter: 78),
    Plate(plateName: "University of Arkansas Medical Sciences", imageCounter: 79),
    Plate(plateName: "University of Central Arkansas 1st Design", imageCounter: 80),
    Plate(plateName: "University of Central Arkansas 2nd Design", imageCounter: 81),
    Plate(plateName: "Zeta Phi Beta Sorority ", imageCounter: 82),
    Plate(plateName: "Municipal Police Association", imageCounter: 83),
    Plate(plateName: "Arkansas Sheriffs' Association", imageCounter: 84),
    Plate(plateName: "Arkansas' Emergency Medical Services", imageCounter: 85),
    Plate(plateName: "Arkansas Firefighter", imageCounter: 86),
    Plate(plateName: "Firefighters' Memorial", imageCounter: 87),
    Plate(plateName: "Retired Firefighter", imageCounter: 88),
    Plate(plateName: "Justice of the Peace", imageCounter: 89),
    Plate(plateName: "Professional Firefighter ", imageCounter: 90),
    Plate(plateName: "Search & Rescue", imageCounter: 91),
    Plate(plateName: "Sheep Dog", imageCounter: 92),
    Plate(plateName: "Ambulance", imageCounter: 93),
    Plate(plateName: "Armed Forces Reserve", imageCounter: 94),
    Plate(plateName: "Armed Forces Retired", imageCounter: 95),
    Plate(plateName: "Arkansas Civil Air Patrol", imageCounter: 96),
    Plate(plateName: "Cold War Veteran", imageCounter: 97),
    Plate(plateName: "Congressional Medal of Honor ", imageCounter: 98),
    Plate(plateName: "Arkansas Disabled Veteran", imageCounter: 99),
    Plate(plateName: "Arkansas' Distinguished Flying Cross", imageCounter: 100),
    Plate(plateName: "Arkansas' Ex-Prisoner of War", imageCounter: 101),
    Plate(plateName: "Arkansas' Gold Star Family", imageCounter: 102),
    Plate(plateName: "Arkansas' Korean War Veteran", imageCounter: 103),
    Plate(plateName: "Retired Merchant Marine", imageCounter: 104),
    Plate(plateName: "Arkansas' National Guard", imageCounter: 105),
    Plate(plateName: "Arkansas Operation Enduring Freedom Veteran", imageCounter: 106),
    Plate(plateName: "Arkansas Operation Iraqi Freedom Veteran", imageCounter: 107),
    Plate(plateName: "Arkansas' Amateur Radio", imageCounter: 108),
    Plate(plateName: "Arkansas' Realtor", imageCounter: 109),
    Plate(plateName: "Tennis", imageCounter: 110),
    Plate(plateName: "Golf Association", imageCounter: 111),
    Plate(plateName: "Little Rock Rangers", imageCounter: 112),
    Plate(plateName: "Antique Motorcycle", imageCounter: 113),
    Plate(plateName: "Antique Vehicle", imageCounter: 114),
    Plate(plateName: "Church Bus", imageCounter: 115),
    Plate(plateName: "Not For Hire Bus", imageCounter: 116),
    Plate(plateName: "Personalized Motorcycle", imageCounter: 117),
    Plate(plateName: "Disabled Motorcycle", imageCounter: 118),
    Plate(plateName: "Arkansas' Purple Heart - Motorcycle", imageCounter: 119),
    Plate(plateName: "School Vehicle", imageCounter: 120),
    Plate(plateName: "Arkansas Street Rod", imageCounter: 121),
    Plate(plateName: "Taxi Cab For Hire", imageCounter: 122),
    Plate(plateName: "Transporter", imageCounter: 123),
    Plate(plateName: "Veteran of Foreign Wars Motorcycle", imageCounter: 124)
    ])
}
