//
//  Colorado.swift
//  License Plate Search
//
//  Created by Jared Detro on 6/30/20.
//  Copyright © 2020 Jared Detro. All rights reserved.
//

import Foundation

extension State {
    static let colorado = State(name: "Colorado", plates: [
        Plate(plateName: "Colorado Standard", imageCounter: 0),
        Plate(plateName: "Standard Designer", imageCounter: 1),
        Plate(plateName: "Disabled 1st Design", imageCounter: 2),
        Plate(plateName: "Disabled 2nd Design", imageCounter: 3),
        Plate(plateName: "Carbon Fund", imageCounter: 4),
        Plate(plateName: "Columbine", imageCounter: 5),
        Plate(plateName: "Protect Our Rivers", imageCounter: 6),
        Plate(plateName: "Pueblo Chile", imageCounter: 7),
        Plate(plateName: "Respect Wildlife", imageCounter: 8),
        Plate(plateName: "Mesa Verde National Park", imageCounter: 9),
        Plate(plateName: "Rocky Mountain National Park", imageCounter: 10),
        Plate(plateName: "Colorado State Parks", imageCounter: 11),
        Plate(plateName: "Support The Horse", imageCounter: 12),
        Plate(plateName: "Wildlife Sporting", imageCounter: 13),
        Plate(plateName: "Adopt a Shelter Pet", imageCounter: 14),
        Plate(plateName: "ALS Association 1st Design", imageCounter: 15),
        Plate(plateName: "ALS Association 2nd Design", imageCounter: 16),
        Plate(plateName: "Support Aviation 1st Design", imageCounter: 17),
        Plate(plateName: "Support Aviation 2nd Design", imageCounter: 18),
        Plate(plateName: "Colorado's Boy Scouts of America", imageCounter: 19),
        Plate(plateName: "Support Breast Cancer", imageCounter: 20),
        Plate(plateName: "Cure Childhood Cancer", imageCounter: 21),
        Plate(plateName: "Child Loss Awareness", imageCounter: 22),
        Plate(plateName: "Colorado Avalanche", imageCounter: 23),
        Plate(plateName: "Donate Life", imageCounter: 24),
        Plate(plateName: "Colorado's Girl Scouts", imageCounter: 25),
        Plate(plateName: "Greyhound Lovers", imageCounter: 26),
        Plate(plateName: "Juvenile Diabetes Research Foundation", imageCounter: 27),
        Plate(plateName: "Support Education", imageCounter: 28),
        Plate(plateName: "Air Force Academy", imageCounter: 29),
        Plate(plateName: "Colorado College", imageCounter: 30),
        Plate(plateName: "Colorado School of Mines", imageCounter: 31),
        Plate(plateName: "Colorado State University", imageCounter: 32),
        Plate(plateName: "Colorado State University - Pueblo", imageCounter: 33),
        Plate(plateName: "Colorado Mesa University", imageCounter: 34),
        Plate(plateName: "Fort Lewis College", imageCounter: 35),
        Plate(plateName: "Metropolitan State University of Denver", imageCounter: 36),
        Plate(plateName: "Regis University", imageCounter: 37),
        Plate(plateName: "University of Colorado", imageCounter: 38),
        Plate(plateName: "University of Denver", imageCounter: 39),
        Plate(plateName: "University of Northern Colorado", imageCounter: 40),
        Plate(plateName: "Western Colorado University", imageCounter: 41),
        Plate(plateName: "Craig Hospital", imageCounter: 42),
        Plate(plateName: "Colorado's Emergency Medical Services", imageCounter: 43),
        Plate(plateName: "Fallen Hero", imageCounter: 44),
        Plate(plateName: "Colorado Firefighters", imageCounter: 45),
        Plate(plateName: "Flight For Life", imageCounter: 46),
        Plate(plateName: "State Patrol", imageCounter: 47),
        Plate(plateName: "American Indian Scholars 1st Design", imageCounter: 48),
        Plate(plateName: "American Indian Scholars 2nd Design", imageCounter: 49),
        Plate(plateName: "Government", imageCounter: 50),
        Plate(plateName: "Honorary Consul", imageCounter: 51),
        Plate(plateName: "Representative House District", imageCounter: 52),
        Plate(plateName: "Senator Senate District", imageCounter: 53),
        Plate(plateName: "U.S. Representative", imageCounter: 54),
        Plate(plateName: "U.S. Senator", imageCounter: 55),
        Plate(plateName: "Air Force Commemorative", imageCounter: 56),
        Plate(plateName: "Support The Troops", imageCounter: 57),
        Plate(plateName: "Support The 10th Mountain Division", imageCounter: 58),
        Plate(plateName: "4th Infantry Division", imageCounter: 59),
        Plate(plateName: "4th Infantry Division Disabled", imageCounter: 60),
        Plate(plateName: "Air Force Cross", imageCounter: 61),
        Plate(plateName: "Air Force Cross Disabled", imageCounter: 62),
        Plate(plateName: "Colorado Bronze Star", imageCounter: 63),
        Plate(plateName: "Bronze Star Disabled", imageCounter: 64),
        Plate(plateName: "Bronze Star of Valor", imageCounter: 65),
        Plate(plateName: "Colorado Civil Air Patrol", imageCounter: 66),
        Plate(plateName: "Civil Air Patrol Disabled", imageCounter: 67),
        Plate(plateName: "Colorado Disabled Veteran", imageCounter: 68),
        Plate(plateName: "Disabled Veteran Handicapped", imageCounter: 69),
        Plate(plateName: "Colorado Distinguished Flying Cross", imageCounter: 70),
        Plate(plateName: "Distinguished Flying Cross Disabled", imageCounter: 71),
        Plate(plateName: "Distinguished Service Cross Disabled", imageCounter: 72),
        Plate(plateName: "Fallen Air Force", imageCounter: 73),
        Plate(plateName: "Fallen Air Force Disabled", imageCounter: 74),
        Plate(plateName: "Fallen Army", imageCounter: 75),
        Plate(plateName: "Fallen Army Disabled", imageCounter: 76),
        Plate(plateName: "Fallen Coast Guard", imageCounter: 77),
        Plate(plateName: "Fallen Coast Guard Disabled", imageCounter: 78),
        Plate(plateName: "Fallen Marine", imageCounter: 79),
        Plate(plateName: "Fallen Marine Disabled", imageCounter: 80),
        Plate(plateName: "Fallen Navy", imageCounter: 81),
        Plate(plateName: "Fallen Navy Disabled", imageCounter: 82),
        Plate(plateName: "Honorably Discharged Veteran", imageCounter: 83),
        Plate(plateName: "Honorably Discharged Veteran Disabled", imageCounter: 84),
        Plate(plateName: "Colorado Korean War Veteran", imageCounter: 85),
        Plate(plateName: "Korean War Veteran Disabled", imageCounter: 86),
        Plate(plateName: "Colorado Medal of Honor", imageCounter: 87),
        Plate(plateName: "Medal of Honor Disabled", imageCounter: 88),
        Plate(plateName: "Colorado National Guard", imageCounter: 89),
        Plate(plateName: "Navy Cross", imageCounter: 90),
        Plate(plateName: "Navy Cross Disabled", imageCounter: 91),
        Plate(plateName: "NORAD", imageCounter: 92),
        Plate(plateName: "NORAD Disabled", imageCounter: 93),
        Plate(plateName: "Colorado Pearl Harbor Survivor", imageCounter: 94),
        Plate(plateName: "Pearl Harbor Survivor Disabled", imageCounter: 95),
        Plate(plateName: "Prisoner of War", imageCounter: 96),
        Plate(plateName: "Prisoner of War Disabled", imageCounter: 97),
        Plate(plateName: "Purple Heart", imageCounter: 98),
        Plate(plateName: "Purple Heart Disabled", imageCounter: 99),
        Plate(plateName: "Silver Star Disabled", imageCounter: 100),
        Plate(plateName: "Submarine Service", imageCounter: 101),
        Plate(plateName: "Submarine Service Disabled", imageCounter: 102),
        Plate(plateName: "UDT SEAL", imageCounter: 103),
        Plate(plateName: "UDT SEAL Disabled", imageCounter: 104),
        Plate(plateName: "U.S. Air Force", imageCounter: 105),
        Plate(plateName: "U.S. Air Force Disabled", imageCounter: 106),
        Plate(plateName: "U.S. Army", imageCounter: 107),
        Plate(plateName: "U.S. Army Disabled", imageCounter: 108),
        Plate(plateName: "U.S. Army 10th Mountain Division", imageCounter: 109),
        Plate(plateName: "U.S. Army 10th Mountain Division Disabled", imageCounter: 110),
        Plate(plateName: "U.S. Army Special Forces", imageCounter: 112),
        Plate(plateName: "U.S. Army Special Forces Disabled", imageCounter: 113),
        Plate(plateName: "U.S. Coast Guard", imageCounter: 114),
        Plate(plateName: "U.S. Coast Guard Disabled", imageCounter: 115),
        Plate(plateName: "U.S. Marine Corps", imageCounter: 116),
        Plate(plateName: "U.S. Marine Corps Disabled", imageCounter: 117),
        Plate(plateName: "U.S. Navy", imageCounter: 118),
        Plate(plateName: "U.S. Navy Disabled", imageCounter: 119),
        Plate(plateName: "U.S. Woman Veteran", imageCounter: 120),
        Plate(plateName: "U.S. Woman Veteran Disabled", imageCounter: 121),
        Plate(plateName: "USS Colorado", imageCounter: 122),
        Plate(plateName: "USS Colorado Disabled", imageCounter: 123),
        Plate(plateName: "Veteran of the Afghanistan War", imageCounter: 124),
        Plate(plateName: "Veteran of teh Afghanistan War", imageCounter: 125),
        Plate(plateName: "Veteran of the Iraq War", imageCounter: 126),
        Plate(plateName: "Veteran of the Iraq War Disabled", imageCounter: 127),
        Plate(plateName: "Veteran of Operations Desert Shield, Storm", imageCounter: 128),
        Plate(plateName: "Veteran of Operations Desert Shield, Storm Disabled", imageCounter: 129),
        Plate(plateName: "World War II Veteran", imageCounter: 130),
        Plate(plateName: "World War II Veteran Disabled", imageCounter: 131),
        Plate(plateName: "Vietnam Veteran", imageCounter: 132),
        Plate(plateName: "Vietnam Veteran Disabled", imageCounter: 133),
        Plate(plateName: "Colorado's Amateur Radio", imageCounter: 134),
        Plate(plateName: "Italian American", imageCounter: 135),
        Plate(plateName: "Kids 1st", imageCounter: 136),
        Plate(plateName: "Pioneer", imageCounter: 137),
        Plate(plateName: "Amateur Call Letter", imageCounter: 138),
        Plate(plateName: "Commercial Call Letter", imageCounter: 139),
        Plate(plateName: "Broncos Country", imageCounter: 140),
        Plate(plateName: "Colorado Rockies", imageCounter: 141),
        Plate(plateName: "Denver Nuggets", imageCounter: 142),
        Plate(plateName: "Share The Road", imageCounter: 143),
        Plate(plateName: "Ski Country", imageCounter: 144),
        Plate(plateName: "Standard Truck", imageCounter: 145),
        Plate(plateName: "Standard Motorcycle", imageCounter: 146),
        Plate(plateName: "Disabled Motorcycle 1st Design", imageCounter: 147),
        Plate(plateName: "Disabled Motorcycle 2nd Design", imageCounter: 148),
        Plate(plateName: "Trailer", imageCounter: 149),
        Plate(plateName: "Recreational Truck", imageCounter: 150),
        Plate(plateName: "Collector Vehicle", imageCounter: 151),
        Plate(plateName: "Collector Truck, Tractor", imageCounter: 152),
        Plate(plateName: "Apportioned Truck", imageCounter: 153),
        Plate(plateName: "Apportioned Trailer", imageCounter: 154),
        Plate(plateName: "Apportioned Permanent", imageCounter: 155),
        Plate(plateName: "Commercial Fleet", imageCounter: 156),
        Plate(plateName: "Dealer Demo", imageCounter: 157),
        Plate(plateName: "Dealer Full-Use", imageCounter: 158),
        Plate(plateName: "Dealer In-Transit", imageCounter: 159),
        Plate(plateName: "Depot Tag", imageCounter: 160),
        Plate(plateName: "Farm Tractor", imageCounter: 161),
        Plate(plateName: "Farm Truck", imageCounter: 162),
        Plate(plateName: "GVW Truck", imageCounter: 163),
        Plate(plateName: "Horseless Carriage", imageCounter: 164),
        Plate(plateName: "Livery", imageCounter: 165),
        Plate(plateName: "Manufacturer", imageCounter: 166),
        Plate(plateName: "SMM Dealer Demo", imageCounter: 167),
        Plate(plateName: "SMM Exempt", imageCounter: 168),
        Plate(plateName: "Special Mobile Machine", imageCounter: 169),
        Plate(plateName: "Special Use Truck", imageCounter: 170),
        Plate(plateName: "Street Rod", imageCounter: 171),
        Plate(plateName: "Taxi Cab", imageCounter: 172),
        Plate(plateName: "Tow Truck", imageCounter: 173),
        Plate(plateName: "Transporter", imageCounter: 174),
        Plate(plateName: "TVW (GVW Tractor)", imageCounter: 175),
    ])
}
